In [12]:
import torch

loaded_data = torch.load('./chord_tensor.pt')
print(loaded_data.shape)
loaded_data = loaded_data[:100]
# Print to verify it's correct
print(loaded_data)
print(loaded_data.shape)

torch.Size([46188, 2048])
tensor([[135, 125, 103,  ...,   0,   0,   0],
        [135, 114, 114,  ...,   0,   0,   0],
        [135,  48,  72,  ...,   0,   0,   0],
        ...,
        [135,  78, 133,  ...,   0,   0,   0],
        [135,  15,  16,  ...,   0,   0,   0],
        [135,  83,  37,  ...,   0,   0,   0]], dtype=torch.int16)
torch.Size([100, 2048])


In [16]:
print(loaded_data[0])
print(loaded_data[0].shape)
for idx, i in enumerate(loaded_data):
    print(i)
    if idx == 10:
        print("------------------")
        continue

tensor([135, 125, 103,  ...,   0,   0,   0], dtype=torch.int16)
torch.Size([2048])
tensor([135, 125, 103,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135, 114, 114,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  48,  72,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  28,  28,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135, 133,  37,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  30,  28,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  92,  16,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  26,  83,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,   4,   4,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,   4,   4,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135, 103,  29,  ...,   0,   0,   0], dtype=torch.int16)
------------------
tensor([135,  60,  28,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135, 103, 105,  ...,   0,   0,   0], dtype=torch.int16)
tensor([135,  83, 111,  ...,   0,   0,   0], dtype=torch.int16)
te

In [7]:
a = torch.zeros((1,2), dtype=torch.int16)
print(a)
a[0,1] = 1
print(a)

tensor([[0, 0]], dtype=torch.int16)
tensor([[0, 1]], dtype=torch.int16)


In [1]:
import torch

loaded_data = torch.load('./inst_tensor.pt')
print(loaded_data.shape)
loaded_data = loaded_data[:100]
# Print to verify it's correct
# print(loaded_data)
print(loaded_data.shape)

# for data in loaded_data:
#     for line in data:
#         print(line)

torch.Size([46188, 2048, 32])
torch.Size([100, 2048, 32])


In [2]:
for data in loaded_data:
    for idx, line in enumerate(data):
        if idx == 100:
            print("-----------------------------------------------")
            break
        print(line)

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2], dtype=torch.int16)
tensor([132,  46,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1], dtype=torch.int16)
tensor([46,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       dtype=torch.int16)
tensor([46,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       dtype=torch.int16)
tensor([46,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       dtype=torch.int16)
tensor([132,  46,  44,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1, 

In [12]:
import torch

m1 = torch.load('./inst_tensor_1234.pt')
m2 = torch.load('./inst_tensor_50000.pt')

merge = torch.cat((m1, m2), dim=0)
print(merge.shape)

torch.Size([46188, 2048, 32])


In [13]:
torch.save(merge, f'./inst_tensor.pt')

In [14]:
import torch

test = torch.load('./inst_tensor.pt')

print(test.shape)

torch.Size([46188, 2048, 32])
